### ISSUE TITLE
Roles attribute missing in Account object

### ISSUE THREAD

**Issue by miniskulljob** [MahanRahmati/mastodon-entities#4]
I think there's a discrepancy in the Mastodon API documentation because they mention that there's a `role` attribute in the `Account` object, but in reality its name is `roles` and it's an array of `Role` objects.

Could you implement it, please?

**Comment by MahanRahmati** [comment]
They have an open task for it in https://github.com/mastodon/documentation/issues/1211.
I will add it later.

**Comment by nikclayton** [comment]
See also https://github.com/mastodon/mastodon/issues/28327
